baseURL = 'https://georgebwang.github.io/'
title = 'Zero'

# multi-language support
defaultContentLanguage = 'en'

# enable git info
enableGitInfo = true

# disable taxonomy, term and RSS (which removes categories, tags and index.xml)
disableKinds = ["taxonomy", "term", "RSS"]

[languages]
  [languages.en]

    [languages.en.params]
      author = "George Baihan Wang"
      description = "PhD Candidate in Finance"
    
    [[languages.en.menu.main]]
      name = 'About'
      url = '#about'
      weight = 1

    [[languages.en.menu.main]]
      name = 'Research'
      url = '#research'
      weight = 20

    [[languages.en.menu.main]]
      name = 'Teaching'
      url = '#teaching'
      weight = 30
      
[params]
  profilePicture = "images/avatar.jpg"
  enableDarkMode = false
  
  [[params.social]]
    name = "github"
    url = "https://github.com/georgebwang"
    icon = "fab fa-github"
  [[params.social]]
    name = "email"
    url = "mailto:george.wang@monash.edu"
    icon = "fas fa-envelope"
  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/george-baihan-wang"
    icon = "fab fa-linkedin"


[build]
  writeStats = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
